language: php
dist: trusty
php:
  - 5.6
  - 5.4
  - 7.0
  - 7.1
  - hhvm
install:
  - test -f ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini && echo "short_open_tag=On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || true
  - composer install
script: ./vendor/bin/phpunit tests/*
